# Granger Causality Testing

In [2]:
%matplotlib inline

import scipy
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sb
import json
import numpy as np
import pandas as pd
from pandas import DataFrame
import xlrd

import seaborn as sns
from pandas.core import datetools


from statsmodels.tsa.stattools import grangercausalitytests

In [5]:
btc = pd.read_csv('/Users/admin/Google Drive/College/Masters - MCM/Semester 2/CA683 - Data Analytics & Mining/Assignment/Asignment 2/Data/BitcoinUSD.csv')

In [16]:
btc_articles_2017 = pd.read_csv('/Users/admin/Google Drive/College/Masters - MCM/Semester 2/CA683 - Data Analytics & Mining/Assignment/Asignment 2/Data/BTC_GDELT_2017.csv')

/Users/admin/PycharmProjects/CA684Homework/venv/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [47]:
btc_tone = pd.read_csv('/Users/admin/Google Drive/College/Masters - MCM/Semester 2/CA683 - Data Analytics & Mining/Assignment/Asignment 2/Data/SimpleToneData.csv')

In [12]:
btc['date'] = pd.to_datetime(btc['date'])
btc.set_index(btc['date'])

date          open          high           low         close  \
date                                                                            
2015-02-20 2015-02-20    240.250118    245.000000    240.250000    240.250000   
2015-02-22 2015-02-22    245.000000    249.000000    235.000000    235.000000   
2015-02-23 2015-02-23    235.000002    235.001000    235.000000    235.000000   
2015-02-24 2015-02-24    235.000000    239.750000    235.000000    239.750000   
2015-02-26 2015-02-26    237.750000    239.800000    237.750000    238.500000   
2015-02-27 2015-02-27    238.500000    249.000000    238.500000    249.000000   
2015-02-28 2015-02-28    240.000000    251.000000    240.000000    240.000060   
2015-03-01 2015-03-01    240.000121    251.000000    240.000121    251.000000   
2015-03-02 2015-03-02    252.000000    269.000000    251.000000    269.000000   
2015-03-03 2015-03-03    268.000000    274.500000    255.000000    267.220000   
2015-03-04 2015-03-04    258.875000    280.000000    258.875000    280.000000   
2015-03-05 2015-03-05    257.000000    280.890000    257.000000    257.000120   
2015-03-06 2015-03-06    269.000141    271.002000    260.000000    260.000000   
2015-03-08 2015-03-08    265.000000    275.002000    260.000031    260.000031   
2015-03-09 2015-03-09    260.000031    285.000000    260.000031    264.000005   
2015-03-10 2015-03-10    264.000064    291.000000    264.000064    291.000000   
2015-03-11 2015-03-11    279.000106    292.950111    276.000000    276.000000   
2015-03-13 2015-03-13    276.000001    301.000000    275.110000    275.110000   
2015-03-15 2015-03-15    275.100000    282.108000    275.100000    282.108000   
2015-03-18 2015-03-18    275.000000    282.000000    262.090000    262.090000   
2015-03-20 2015-03-20    254.898951    267.976676    254.823433    263.560831   
2015-03-22 2015-03-22    265.137848    267.516848    263.773410    267.516848   
2015-03-23 2015-03-23    270.329460    274.298098    260.673511    260.673511   
2015-03-24 2015-03-24    263.018955    271.596048    242.525500    242.525507   
2015-03-25 2015-03-25    273.000000    273.000000    247.475515    247.475515   
2015-03-27 2015-03-27    253.220110    253.352700    242.917500    253.352700   
2015-03-28 2015-03-28    243.681902    258.880679    243.681900    248.728496   
2015-03-30 2015-03-30    242.525500    254.352794    242.525500    254.352794   
2015-03-31 2015-03-31    253.541400    253.730100    242.525500    249.338530   
2015-04-01 2015-04-01    239.870000    250.000000    239.870000    249.000000   
...               ...           ...           ...           ...           ...   
2018-02-22 2018-02-22  10441.060500  10912.000000   9722.224192   9845.538082   
2018-02-23 2018-02-23   9826.555155  10405.499599   9559.970231  10149.240000   
2018-02-24 2018-02-24  10148.000000  10490.000000   9360.000000   9700.000000   
2018-02-25 2018-02-25   9690.613474   9845.000000   9247.718549   9559.197780   
2018-02-26 2018-02-26   9560.197757  10455.000000   9358.529276  10338.048837   
2018-02-27 2018-02-27  10330.511600  10879.000000  10121.000000  10589.174340   
2018-02-28 2018-02-28  10588.153200  11074.000000  10252.000000  10322.067296   
2018-03-01 2018-03-01  10322.067296  11080.000000  10201.124400  10936.784498   
2018-03-02 2018-03-02  10934.198000  11193.000000  10777.000000  11022.243806   
2018-03-03 2018-03-03  11014.271600  11539.439994  11014.271600  11441.000001   
2018-03-04 2018-03-04  11460.000000  11547.367796  11075.484343  11500.605200   
2018-03-05 2018-03-05  11514.607945  11700.000000  11417.000000  11434.999999   
2018-03-07 2018-03-07  10719.574453  10893.759632   9424.000000   9909.604137   
2018-03-08 2018-03-08   9909.604137  10109.770835   9070.000000   9281.943701   
2018-03-09 2018-03-09   9298.629363   9410.561389   8359.320400   9230.488667   
2018-03-10 2018-03-10   9215.907643   9510.000000   8680.000000   8760.776800   
2018-03-11 2018-03-11   8769.000000   9726.22913

In [30]:
btc_articles_2017['Date'] = pd.to_datetime(btc_articles_2017['Date'])
btc_articles_2017 = btc_articles_2017.set_index(btc_articles_2017['Date'])

In [33]:
btc_price_2017 = btc[btc['date'].dt.year == 2017]
btc_price_2017 = btc_price_2017.set_index(btc_price_2017['date'])

In [55]:
btc_tone = btc_tone.rename(index=str, columns={"05/01/2014": "date", "-1.45498984076424": "tone"})
btc_tone['date'] = pd.to_datetime(btc_tone['date'])
btc_tone_2017 = btc_tone[btc_tone['date'].dt.year == 2017]
btc_tone_2017 = btc_tone_2017.set_index(btc_tone_2017['date'])

# Data Processing

In [41]:
# Here we exctract the daily number of articles that matched our search for 'Bitcoin'
articles = btc_articles_2017['NumArticles'].groupby(btc_articles_2017['DateSerial'])
dates = []
numArticles = []
for key, value in articles:
    dates.append(key)
    numArticles.append(value.sum())
len(numArticles)

365

In [57]:
btc_tone_2017['num_articles'] = numArticles

In [ ]:
# Here we exctract the daily number of articles mentioning 'LEGISLATION' that matched our search for 'Bitcoin'
articles = btc_articles_2017[btc_articles_2017['Themes'].str.contains('LEGISLATION')].groupby(btc_articles_2017['DateSerial'])
legal_articles = []
for key, value in articles:
    legal_articles.append(value.sum())
len(legal_articles)

In [64]:
print(btc_price_2017.shape)
print(btc_tone_2017.shape)

(363, 8)
(365, 3)


In [65]:
btc_2017 = pd.merge(btc_price_2017, btc_tone_2017, how='inner', left_index=True, right_index=True)
print(btc_2017.shape)

(363, 11)


# Granger Causality Testing

### Closing Price vs Number of Articles

In [82]:
# These are the two series for input into our granger causality test
x = np.asarray(btc_2017[['close', 'num_articles']])

grangercausalitytests(x, 10, addconst=True, verbose=True)

# We find predictions of the closing price are indeed improved upon considering past values of the numArticles variable
# as opposed to predictions based on just past values of the closing price itself.



Granger Causality
('number of lags (no zero)', 1)
ssr based F test:         F=3.3623  , p=0.0675  , df_denom=359, df_num=1
ssr based chi2 test:   chi2=3.3904  , p=0.0656  , df=1
likelihood ratio test: chi2=3.3746  , p=0.0662  , df=1
parameter F test:         F=3.3623  , p=0.0675  , df_denom=359, df_num=1

Granger Causality
('number of lags (no zero)', 2)
ssr based F test:         F=2.3882  , p=0.0933  , df_denom=356, df_num=2
ssr based chi2 test:   chi2=4.8435  , p=0.0888  , df=2
likelihood ratio test: chi2=4.8113  , p=0.0902  , df=2
parameter F test:         F=2.3882  , p=0.0933  , df_denom=356, df_num=2

Granger Causality
('number of lags (no zero)', 3)
ssr based F test:         F=8.9768  , p=0.0000  , df_denom=353, df_num=3
ssr based chi2 test:   chi2=27.4645 , p=0.0000  , df=3
likelihood ratio test: chi2=26.4672 , p=0.0000  , df=3
parameter F test:         F=8.9768  , p=0.0000  , df_denom=353, df_num=3

Granger Causality
('number of lags (no zero)', 4)
ssr based F test:         F=

{1: ({'lrtest': (3.3745924788263437, 0.06620895198755943, 1),
   'params_ftest': (3.3622735835057482, 0.0675336230049166, 359.0, 1),
   'ssr_chi2test': (3.3903705772243375, 0.06557820880479495, 1),
   'ssr_ftest': (3.3622735834904343, 0.06753362300553797, 359.0, 1)},
   array([[0., 1., 0.]])]),
 2: ({'lrtest': (4.811305023610657, 0.0902066155203509, 2),
   'params_ftest': (2.3882125819517026, 0.09326286897014735, 356.0, 2),
   'ssr_chi2test': (4.843509786991867, 0.08876570633498072, 2),
   'ssr_ftest': (2.388212581951669, 0.09326286897015038, 356.0, 2)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'lrtest': (26.467237674331955, 7.613298394646358e-06, 3),
   'params_ftest': (8.976810579033126, 9.587709960731028e-06, 353.0, 3),
   'ssr_chi2test': (27.46446296134787, 4.704582626670074e-06, 3),
   'ssr_ftest': (8.976810579033147, 9.587709960730858e-06, 353.0, 3)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0.

In [83]:
# Checking other direction

x = np.asarray(btc_2017[['num_articles', 'close']])

grangercausalitytests(x, 10, addconst=True, verbose=True)

# We find that there is even stronger evidence that the number of articles depends upon the
# closing price from previous periods. 



Granger Causality
('number of lags (no zero)', 1)
ssr based F test:         F=47.0948 , p=0.0000  , df_denom=359, df_num=1
ssr based chi2 test:   chi2=47.4883 , p=0.0000  , df=1
likelihood ratio test: chi2=44.6216 , p=0.0000  , df=1
parameter F test:         F=47.0948 , p=0.0000  , df_denom=359, df_num=1

Granger Causality
('number of lags (no zero)', 2)
ssr based F test:         F=25.1867 , p=0.0000  , df_denom=356, df_num=2
ssr based chi2 test:   chi2=51.0809 , p=0.0000  , df=2
likelihood ratio test: chi2=47.7753 , p=0.0000  , df=2
parameter F test:         F=25.1867 , p=0.0000  , df_denom=356, df_num=2

Granger Causality
('number of lags (no zero)', 3)
ssr based F test:         F=13.5881 , p=0.0000  , df_denom=353, df_num=3
ssr based chi2 test:   chi2=41.5727 , p=0.0000  , df=3
likelihood ratio test: chi2=39.3424 , p=0.0000  , df=3
parameter F test:         F=13.5881 , p=0.0000  , df_denom=353, df_num=3

Granger Causality
('number of lags (no zero)', 4)
ssr based F test:         F=

{1: ({'lrtest': (44.621635500017874, 2.3903556769081075e-11, 1),
   'params_ftest': (47.09477769318318, 2.9786476755353175e-11, 359.0, 1),
   'ssr_chi2test': (47.48832736754799, 5.5332443225799664e-12, 1),
   'ssr_ftest': (47.09477769323129, 2.978647675470649e-11, 359.0, 1)},
   array([[0., 1., 0.]])]),
 2: ({'lrtest': (47.775334326351185, 4.223942188006929e-11, 2),
   'params_ftest': (25.186686959309966, 5.88038934933838e-11, 356.0, 2),
   'ssr_chi2test': (51.0808651253421, 8.089674968023195e-12, 2),
   'ssr_ftest': (25.186686959309956, 5.88038934933838e-11, 356.0, 2)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'lrtest': (39.34241553980155, 1.4686535495144695e-08, 3),
   'params_ftest': (13.588104935590422, 2.0774045193810422e-08, 353.0, 3),
   'ssr_chi2test': (41.57267232419618, 4.943634321090953e-09, 3),
   'ssr_ftest': (13.588104935593753, 2.077404519371957e-08, 353.0, 3)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.

As expected we have found bi-directional granger causality between the closing price of bitcoin and the number of articles tagged as pertaining to bitcoin. In our previous tests we had not found this to be the case. I believe that we were passing in differenced and transformed data to a method which performs these operations on the raw data. Perhaps double differencing and double transformations were the cause of our previous test results.

### Closing Price vs Normalised Tone

In [84]:
# These are the two series for input into our granger causality test
x = np.asarray(btc_2017[['close', 'tone']])

grangercausalitytests(x, 10, addconst=True, verbose=True)

# Here we find that the tone series gives us no extra predictive power when trying to predict values for closing price



Granger Causality
('number of lags (no zero)', 1)
ssr based F test:         F=0.0962  , p=0.7566  , df_denom=359, df_num=1
ssr based chi2 test:   chi2=0.0970  , p=0.7554  , df=1
likelihood ratio test: chi2=0.0970  , p=0.7554  , df=1
parameter F test:         F=0.0962  , p=0.7566  , df_denom=359, df_num=1

Granger Causality
('number of lags (no zero)', 2)
ssr based F test:         F=0.5129  , p=0.5992  , df_denom=356, df_num=2
ssr based chi2 test:   chi2=1.0403  , p=0.5944  , df=2
likelihood ratio test: chi2=1.0388  , p=0.5949  , df=2
parameter F test:         F=0.5129  , p=0.5992  , df_denom=356, df_num=2

Granger Causality
('number of lags (no zero)', 3)
ssr based F test:         F=0.3867  , p=0.7626  , df_denom=353, df_num=3
ssr based chi2 test:   chi2=1.1831  , p=0.7571  , df=3
likelihood ratio test: chi2=1.1812  , p=0.7575  , df=3
parameter F test:         F=0.3867  , p=0.7626  , df_denom=353, df_num=3

Granger Causality
('number of lags (no zero)', 4)
ssr based F test:         F=

{1: ({'lrtest': (0.09702873328114947, 0.755424833542083, 1),
   'params_ftest': (0.09623752470107942, 0.7565723553300299, 359.0, 1),
   'ssr_chi2test': (0.09704173799947163, 0.7554089672534718, 1),
   'ssr_ftest': (0.09623752470113348, 0.7565723553299811, 359.0, 1)},
   array([[0., 1., 0.]])]),
 2: ({'lrtest': (1.0388080631109915, 0.5948749690577959, 2),
   'params_ftest': (0.512947741221156, 0.5991699070617653, 356.0, 2),
   'ssr_chi2test': (1.0403041268584914, 0.594430150010199, 2),
   'ssr_ftest': (0.5129477412210844, 0.5991699070618006, 356.0, 2)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'lrtest': (1.1811833751744416, 0.7575207625821002, 3),
   'params_ftest': (0.3867060304299558, 0.7626481728212376, 353.0, 3),
   'ssr_chi2test': (1.1831232659045017, 0.7570548302149108, 3),
   'ssr_ftest': (0.38670603042989726, 0.7626481728212854, 353.0, 3)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 

In [85]:
# Checking other direction

x = np.asarray(btc_2017[['tone', 'close']])

grangercausalitytests(x, 10, addconst=True, verbose=True)

# We find again no granger causality in the other direction 



Granger Causality
('number of lags (no zero)', 1)
ssr based F test:         F=0.3454  , p=0.5571  , df_denom=359, df_num=1
ssr based chi2 test:   chi2=0.3483  , p=0.5551  , df=1
likelihood ratio test: chi2=0.3481  , p=0.5552  , df=1
parameter F test:         F=0.3454  , p=0.5571  , df_denom=359, df_num=1

Granger Causality
('number of lags (no zero)', 2)
ssr based F test:         F=0.5896  , p=0.5551  , df_denom=356, df_num=2
ssr based chi2 test:   chi2=1.1958  , p=0.5500  , df=2
likelihood ratio test: chi2=1.1938  , p=0.5505  , df=2
parameter F test:         F=0.5896  , p=0.5551  , df_denom=356, df_num=2

Granger Causality
('number of lags (no zero)', 3)
ssr based F test:         F=0.3334  , p=0.8012  , df_denom=353, df_num=3
ssr based chi2 test:   chi2=1.0201  , p=0.7964  , df=3
likelihood ratio test: chi2=1.0186  , p=0.7967  , df=3
parameter F test:         F=0.3334  , p=0.8012  , df_denom=353, df_num=3

Granger Causality
('number of lags (no zero)', 4)
ssr based F test:         F=

{1: ({'lrtest': (0.34809371130540967, 0.5551942225006068, 1),
   'params_ftest': (0.34537498385343873, 0.5571124537884018, 359.0, 1),
   'ssr_chi2test': (0.3482611257796713, 0.5550991188896417, 1),
   'ssr_ftest': (0.34537498385332044, 0.5571124537884475, 359.0, 1)},
   array([[0., 1., 0.]])]),
 2: ({'lrtest': (1.1938106747504662, 0.5505126536324394, 2),
   'params_ftest': (0.589612323740178, 0.5550828203984979, 356.0, 2),
   'ssr_chi2test': (1.1957867914169045, 0.5499689836505335, 2),
   'ssr_ftest': (0.5896123237457312, 0.5550828203954163, 356.0, 2)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'lrtest': (1.0186325650602157, 0.7967435508654519, 3),
   'params_ftest': (0.33341342024937776, 0.8011942258270575, 353.0, 3),
   'ssr_chi2test': (1.0200750534612588, 0.7963945431842849, 3),
   'ssr_ftest': (0.3334134202516893, 0.8011942258253812, 353.0, 3)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0.,

### Transformed Closing Price vs Average Tone

In [90]:
btc_2017['log_diff_close'] = np.log(btc_2017['close']).diff()
btc_2017['log_close'] = np.log(btc_2017['close'])
btc_2017 = btc_2017.dropna()

In [91]:
# These are the two series for input into our granger causality test
x = np.asarray(btc_2017[['log_diff_close', 'tone']])

grangercausalitytests(x, 10, addconst=True, verbose=True)




Granger Causality
('number of lags (no zero)', 1)
ssr based F test:         F=0.0221  , p=0.8819  , df_denom=358, df_num=1
ssr based chi2 test:   chi2=0.0223  , p=0.8813  , df=1
likelihood ratio test: chi2=0.0223  , p=0.8813  , df=1
parameter F test:         F=0.0221  , p=0.8819  , df_denom=358, df_num=1

Granger Causality
('number of lags (no zero)', 2)
ssr based F test:         F=0.1794  , p=0.8358  , df_denom=355, df_num=2
ssr based chi2 test:   chi2=0.3639  , p=0.8336  , df=2
likelihood ratio test: chi2=0.3637  , p=0.8337  , df=2
parameter F test:         F=0.1794  , p=0.8358  , df_denom=355, df_num=2

Granger Causality
('number of lags (no zero)', 3)
ssr based F test:         F=0.5648  , p=0.6386  , df_denom=352, df_num=3
ssr based chi2 test:   chi2=1.7280  , p=0.6307  , df=3
likelihood ratio test: chi2=1.7238  , p=0.6316  , df=3
parameter F test:         F=0.5648  , p=0.6386  , df_denom=352, df_num=3

Granger Causality
('number of lags (no zero)', 4)
ssr based F test:         F=

{1: ({'lrtest': (0.022289939069196407, 0.881318371099821, 1),
   'params_ftest': (0.02210538656024921, 0.8818907996897437, 358.0, 1),
   'ssr_chi2test': (0.02229062722974456, 0.8813165526481185, 1),
   'ssr_ftest': (0.0221053865602453, 0.8818907996897437, 358.0, 1)},
   array([[0., 1., 0.]])]),
 2: ({'lrtest': (0.36374259680496834, 0.8337086331441629, 2),
   'params_ftest': (0.17943594357039325, 0.8358172350602566, 355.0, 2),
   'ssr_chi2test': (0.3639264207625522, 0.8336320088553536, 2),
   'ssr_ftest': (0.17943594357042508, 0.8358172350602238, 355.0, 2)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'lrtest': (1.7238358449294537, 0.6316476086405307, 3),
   'params_ftest': (0.5647626609965094, 0.638575664398099, 352.0, 3),
   'ssr_chi2test': (1.7279812099239924, 0.6307309546878999, 3),
   'ssr_ftest': (0.5647626609965137, 0.638575664398099, 352.0, 3)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0.

In [92]:
# These are the two series for input into our granger causality test
x = np.asarray(btc_2017[['tone', 'log_diff_close']])

grangercausalitytests(x, 10, addconst=True, verbose=True)




Granger Causality
('number of lags (no zero)', 1)
ssr based F test:         F=1.6293  , p=0.2026  , df_denom=358, df_num=1
ssr based chi2 test:   chi2=1.6429  , p=0.1999  , df=1
likelihood ratio test: chi2=1.6392  , p=0.2004  , df=1
parameter F test:         F=1.6293  , p=0.2026  , df_denom=358, df_num=1

Granger Causality
('number of lags (no zero)', 2)
ssr based F test:         F=0.8765  , p=0.4171  , df_denom=355, df_num=2
ssr based chi2 test:   chi2=1.7777  , p=0.4111  , df=2
likelihood ratio test: chi2=1.7733  , p=0.4120  , df=2
parameter F test:         F=0.8765  , p=0.4171  , df_denom=355, df_num=2

Granger Causality
('number of lags (no zero)', 3)
ssr based F test:         F=0.5647  , p=0.6386  , df_denom=352, df_num=3
ssr based chi2 test:   chi2=1.7277  , p=0.6308  , df=3
likelihood ratio test: chi2=1.7236  , p=0.6317  , df=3
parameter F test:         F=0.5647  , p=0.6386  , df_denom=352, df_num=3

Granger Causality
('number of lags (no zero)', 4)
ssr based F test:         F=

{1: ({'lrtest': (1.6391776776283677, 0.20043833137056055, 1),
   'params_ftest': (1.6292518412183348, 0.2026339567712619, 358.0, 1),
   'ssr_chi2test': (1.6429047896084668, 0.1999273849117451, 1),
   'ssr_ftest': (1.6292518412183687, 0.20263395677125207, 358.0, 1)},
   array([[0., 1., 0.]])]),
 2: ({'lrtest': (1.7733301584742094, 0.41202754328357805, 2),
   'params_ftest': (0.8765073153140933, 0.41713294857647154, 355.0, 2),
   'ssr_chi2test': (1.7777049775385245, 0.4111272553161006, 2),
   'ssr_ftest': (0.8765073153141336, 0.417132948576447, 355.0, 2)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'lrtest': (1.7235965867535015, 0.6317005395695172, 3),
   'params_ftest': (0.5646840869741728, 0.6386279741506551, 352.0, 3),
   'ssr_chi2test': (1.7277408002022128, 0.6307840940385661, 3),
   'ssr_ftest': (0.5646840869741679, 0.6386279741506551, 352.0, 3)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0.,